kind: pipeline
type: docker
name: default
 
trigger:
  branch: 
  - main
  event: 
  - push
 
steps:
- name: node
  image: node:10-alpine
  commands:
    - cd backend
    - npm install
    - npm run test
