kind: pipeline
type: docker
name: default
 
clone:
  depth: 1
 
steps:
# - name: node
#   image: node:10-alpine
#   commands:
#     - cd backend
#     - npm install
#     - npm run test
#   when:
#     branch:
#       - main

- name: make .env
  image: alpine
  environment:
      MYSQL_PORT:
        from_secret: MYSQL_PORT
      MYSQL_HOST:
        from_secret: MYSQL_HOST
      MYSQL_USERNAME:
        from_secret: MYSQL_USERNAME
      MYSQL_PASSWORD:
        from_secret: MYSQL_PASSWORD
      MYSQL_DB:
        from_secret: MYSQL_DB
  commands:
  - ls
  - echo "MYSQL_PORT:" $MYSQL_PORT > ./backend/.env
  - echo "MYSQL_HOST:" $MYSQL_HOST >> ./backend/.env
  - echo "MYSQL_USERNAME:" $MYSQL_USERNAME >> ./backend/.env
  - echo "MYSQL_PASSWORD:" $MYSQL_PASSWORD >> ./backend/.env
  - echo "MYSQL_DB:" $MYSQL_DB >> ./backend/.env
  - cat ./backend/.env

- name: docker build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
    repo: frank93011/metis
    context: backend/
    dockerfile: backend/Dockerfile