kind: pipeline
type: docker
name: default
 
clone:
  depth: 1
 
steps:
- name: node
  image: node:10-alpine
  commands:
    - cd backend
    - npm install
    - npm run test
  when:
    branch:
      - main

- name: docker build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
    repo: frank93011/metis
    dockerfile: /Users/frankchen/Documents/github/LINE/metis/backend/Dockerfile